language: c

sudo: false

addons:
  apt:
    packages:
    - socat

before_script:
  - travis_retry pip install --user redis
  - travis_retry pip install --user nose
  - travis_retry pip install --user git+https://github.com/andymccurdy/redis-py.git@2.9.0
  - travis_retry pip install --user git+https://github.com/idning/python-memcached.git#egg=memcache
  - export PATH=$PATH:$HOME/.local/bin

script:
  - bash ./travis.sh

